# Filebeat Configuration for Enterprise Security Platform
filebeat.inputs:
  # Suricata Logs
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      logtype: suricata
      environment: production
    fields_under_root: true
    multiline.pattern: '^\{'
    multiline.negate: true
    multiline.match: after

  # Docker Container Logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

  # System Logs
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/kern.log
    fields:
      logtype: system
      environment: production
    fields_under_root: true

  # pfSense Logs
  - type: syslog
    enabled: true
    protocol.udp:
      host: "0.0.0.0:5514"
    fields:
      logtype: pfsense
      environment: production
    fields_under_root: true

  # Application Logs
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      logtype: application
      environment: production
    fields_under_root: true

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - timestamp:
      field: '@timestamp'
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2023-12-01T10:30:45.123Z'

# Output Configuration
output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  bulk_max_size: 2048
  template.name: "security-platform"
  template.pattern: "security-*"

# Logging Configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTICSEARCH_PASSWORD}"

# Security
ssl.verification_mode: none

# Performance Tuning
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s
