# Prometheus Configuration for Enterprise Security Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'enterprise-security-platform'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AI Detection Service
  - job_name: 'ai-detection'
    static_configs:
      - targets: ['ai-threat-detection:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Incident Response Service
  - job_name: 'incident-response'
    static_configs:
      - targets: ['incident-response:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Suricata Metrics
  - job_name: 'suricata'
    static_configs:
      - targets: ['suricata-exporter:9917']
    scrape_interval: 10s

  # pfSense Metrics
  - job_name: 'pfsense'
    static_configs:
      - targets: ['pfsense-exporter:9876']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Kibana
  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:5601']
    metrics_path: '/api/stats'
    scrape_interval: 30s

  # Docker Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

  # Custom Security Metrics
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['security-metrics-exporter:9999']
    scrape_interval: 5s
    metrics_path: '/security/metrics'

# Remote write configuration for long-term storage
remote_write:
  - url: "http://thanos-receive:19291/api/v1/receive"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
